<?php
/**
 * Used for defining global theme variable
 */

 $watson_social_links = array('Fb' => esc_html__('Facebook', 'watson'),
							'Tw' => esc_html__('Twitter', 'watson'),
							'Be' => esc_html__('Behance', 'watson'),
							'Db' => esc_html__('Dribbble', 'watson'),
							'In' => esc_html__('Instagram', 'watson'),
							'Ld' => esc_html__('Linkedin', 'watson'),
							'Wa' => esc_html__('WhatsApp', 'watson'),
							'Da' => esc_html__('DeviantArt', 'watson'),
							'Dg' => esc_html__('Digg', 'watson'),
							'Fr' => esc_html__('Flickr', 'watson'),
							'Fq' => esc_html__('Foursquare', 'watson'),
							'Gi' => esc_html__('Git', 'watson'),
							'Pn' => esc_html__('Pinterest', 'watson'),
							'Rd' => esc_html__('Reddit', 'watson'),
							'Md' => esc_html__('Medium', 'watson'),
							'Sk' => esc_html__('Skype', 'watson'),
							'Sc' => esc_html__('Souncloud', 'watson'),
							'Su' => esc_html__('Stumbleupon', 'watson'),
							'Tb' => esc_html__('Tumblr', 'watson'),
							'Ya' => esc_html__('Yahoo', 'watson'),
							'Ye' => esc_html__('Yelp', 'watson'),
							'Yt' => esc_html__('Youtube', 'watson'),
							'Vm' => esc_html__('Vimeo', 'watson'),
							'Xg' => esc_html__('Xing', 'watson') );
							
$watson_social_links_icons = array(	'Fb' => 'facebook-square',
									'Tw' => 'twitter-square',
									'Be' => 'behance-square',
									'Db' => 'dribbble-square',
									'In' => 'instagram',
									'Ld' => 'linkedin',
									'Wa' => 'whatsapp-square',
									'Da' => 'deviantart',
									'Dg' => 'digg',
									'Fr' => 'flickr',
									'Fq' => 'foursquare',
									'Gi' => 'git-square',
									'Pn' => 'pinterest-square',
									'Rd' => 'reddit-square',
									'Md' => 'medium',
									'Sk' => 'skype',
									'Sc' => 'soundcloud',
									'Su' => 'stumbleupon',
									'Tb' => 'tumblr-square',
									'Ya' => 'yahoo',
									'Ye' => 'yelp',
									'Yt' => 'youtube-square',
									'Vm' => 'vimeo-square',
									'Xg' => 'xing-square' );

$watson_nav_menu_icons = [
	'none',
	'home',
	'apartment',
	'pencil',
	'magic-wand',
	'drop',
	'lighter',
	'poop',
	'sun',
	'moon',
	'cloud',
	'cloud-upload',
	'cloud-download',
	'cloud-sync',
	'cloud-check',
	'database',
	'lock',
	'cog',
	'trash',
	'dice',
	'heart',
	'star',
	'star-half',
	'star-empty',
	'flag',
	'envelope',
	'paperclip',
	'inbox',
	'eye',
	'printer',
	'file-empty',
	'file-add',
	'enter',
	'exit',
	'graduation-hat',
	'license',
	'music-note',
	'film-play',
	'camera-video',
	'camera',
	'picture',
	'book',
	'bookmark',
	'user',
	'users',
	'shirt',
	'store',
	'cart',
	'tag',
	'phone-handset',
	'phone',
	'pushpin',
	'map-marker',
	'map',
	'location',
	'calendar-full',
	'keyboard',
	'spell-check',
	'screen',
	'smartphone',
	'tablet',
	'laptop',
	'laptop-phone',
	'power-switch',
	'bubble',
	'heart-pulse',
	'construction',
	'pie-chart',
	'chart-bars',
	'gift',
	'diamond',
	'linearicons',
	'dinner',
	'coffee-cup',
	'leaf',
	'paw',
	'rocket',
	'briefcase',
	'bus',
	'car',
	'train',
	'bicycle',
	'wheelchair',
	'select',
	'earth',
	'smile',
	'sad',
	'neutral',
	'mustache',
	'alarm',
	'bullhorn',
	'volume-high',
	'volume-medium',
	'volume-low',
	'volume',
	'mic',
	'hourglass',
	'undo',
	'redo',
	'sync',
	'history',
	'clock',
	'download',
	'upload',
	'enter-down',
	'exit-up',
	'bug',
	'code',
	'link',
	'unlink',
	'thumbs-up',
	'thumbs-down',
	'magnifier',
	'cross',
	'menu',
	'list',
	'chevron-up',
	'chevron-down',
	'chevron-left',
	'chevron-right',
	'arrow-up',
	'arrow-down',
	'arrow-left',
	'arrow-right',
	'move',
	'warning',
	'question-circle',
	'menu-circle',
	'checkmark-circle',
	'cross-circle',
	'plus-circle',
	'circle-minus',
	'arrow-up-circle',
	'arrow-down-circle',
	'arrow-left-circle',
	'arrow-right-circle',
	'chevron-up-circle',
	'chevron-down-circle',
	'chevron-left-circle',
	'chevron-right-circle',
	'crop',
	'frame-expand',
	'frame-contract',
	'layers',
	'funnel',
	'text-format',
	'text-format-remove',
	'text-size',
	'bold',
	'italic',
	'underline',
	'strikethrough',
	'highlight',
	'text-align-left',
	'text-align-center',
	'text-align-right',
	'text-align-justify',
	'line-spacing',
	'indent-increase',
	'indent-decrease',
	'pilcrow',
	'direction-ltr',
	'direction-rtl',
	'page-break',
	'sort-alpha-asc',
	'sort-amount-asc',
	'hand',
	'pointer-up',
	'pointer-right',
	'pointer-down',
	'pointer-left',
];